- name: base setup on all nodes
  hosts: all
  become: true
  roles:
    - common

- name: etcd cluster
  hosts: etcd
  become: true
  roles:
    - etcd

- name: postgresql + patroni
  hosts: postgres
  become: true
  roles:
    - postgres
    - patroni

- name: haproxy
  hosts: loadbalancer
  become: true
  roles:
    - haproxy
